### PR TITLE
updated color and weather message

### PR DESCRIPTION
**Pull request by jmoriarty221B**

### CODE REVIEW

**Comment by yashsriv** [comment]
- In weather script, you don't need to do `t = Math.round(t * 1) / 1`. Just `t = Math.round(t)` will work. That is redundant code.
- You have changed the api key to your own api key adding an extra change for no reason. Please undo that change
- Also you have changed the calendar sc ript to fix the spelling mistake, but that has already been fixed, causing a merge conflict. Please undo that change too.
- If you have changed more than one file but only want ot commit some of them, for example you only wanted to commit the weather script and the css and not the pushbullet script and calendar script, you can use `git add js/weather_script.js` to be more specific about the files aadded to a commit

**Comment by yashsriv** [comment]
Also why did you touch the time_script (i.e. indent) when you did not make any changes in it... there's a reason why it was indented the way it was. :godmode:

**Comment by jmoriarty221B** [comment]
Sorry.... i will fix it and then commit :-)

**Comment by yashsriv** [comment]
What are the classes `two` and `four` ??? Please give meaningful names.

Also you did not run `gg=G` in the most important file(`js/weather_script.js`) but have done that everywhere else :disappointed:

**Pull request merged**
