### PR TITLE
Added video, returns YES if face found, otherwise keeps checking

### PR DESCRIPTION
**Pull request by shubjn**
@yash lookout for the change

### CODE REVIEW

**Comment by yashsriv** [comment]
@shubjn Please clean up the code.... 
- Why are the glasses being mentioned here??? We don't have any glasses.
- where is that delay and the total logic I was talking about?? You can leave that out, @subhdeep will work on that....
- I just want there to be a function which says yes if there is a face and no if there isn't one.... we don't need any animation frame related code...that portion will be in a different loop written by @subhdeep. Please reduce the whole thing to an `init()` function which intializes the video and the detector and a `check()` function which prints yes if there is a face in the image and no if there is no face in the image.

**Comment by yashsriv** [comment]
The check function is inside the play. Please declare it outside the function in global scope. Also `vider_check` is essentially `init` and can be renamed to that to better portray its function

**Comment by shubjn** [comment]
@yash check now

**Comment by yashsriv** [comment]
remove the check call from #L60

**Comment by yashsriv** [comment]
remove the check call from within play

**Pull request merged**
